-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "cover_image" TEXT,
ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "author" SET DATA TYPE TEXT,
ALTER COLUMN "category" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Borrowing" ALTER COLUMN "borrow_date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "due_date" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Member" ADD COLUMN     "profile_image" TEXT,
ALTER COLUMN "username" SET DATA TYPE TEXT,
ALTER COLUMN "password" SET DATA TYPE TEXT,
ALTER COLUMN "first_name" SET DATA TYPE TEXT,
ALTER COLUMN "last_name" SET DATA TYPE TEXT,
ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "phone_number" SET DATA TYPE TEXT,
ALTER COLUMN "membership_date" SET DATA TYPE TIMESTAMP(3);
